version: v1.0.0

baseGoContainer: &baseGoContainer
  name: go
  image: quay.io/deis/lightweight-docker-go:v0.6.0
  sourceMountPath: /go/src/github.com/radu-matei/prototype
  workingDirectory: /go/src/github.com/radu-matei/prototype
  tty: true

baseDoodContainer: &baseDoodContainer
  name: dood
  image: krancour/dind:18.09.5
  sourceMountPath: /go/src/github.com/radu-matei/prototype
  workingDirectory: /go/src/github.com/radu-matei/prototype
  mountDockerSocket: true
  tty: true

baseDindContainer: &baseDindContainer
  name: dind
  image: krancour/dind:18.09.5
  sourceMountPath: /go/src/github.com/radu-matei/prototype
  workingDirectory: /go/src/github.com/radu-matei/prototype
  privileged: true

baseDemoContainer: &baseDemoContainer
  name: demo
  image: debian:stretch

targets:

################################################################################
# Demo targets                                                                 #
################################################################################

  env:
    containers:
    - name: env
      image: debian:stretch
      sourceMountPath: /go/src/github.com/radu-matei/prototype
      workingDirectory: /go/src/github.com/radu-matei/prototype
      command: scripts/env.sh

  foo:
    containers:
    - <<: *baseDemoContainer
      command: echo foo

  bar:
    containers:
    - <<: *baseDemoContainer
      command: echo bar

  fail:
    containers:
    - <<: *baseDemoContainer
      command: "false"

  # This target demonstrates two containers networked together.
  # This doesn't work in Brigade / k8s yet because job / pod completion is based
  # on ALL containers having exited and the redis sidecar never will. There's
  # a KEP open to fix this.
  redis:
    containers:
    - name: redis
      image: redis:latest
    - name: redis-cli
      image: redis:latest
      sourceMountPath: /demo
      workingDirectory: /demo
      command: scripts/demo/redis.sh

################################################################################
# Utility targets                                                              #
################################################################################

  dep:
    containers:
    - <<: *baseGoContainer
      command: dep ensure -v

################################################################################
# Test targets                                                                 #
################################################################################

  verify-vendored-code:
    containers:
    - <<: *baseGoContainer
      command: dep check

  test-unit:
    containers:
    - <<: *baseGoContainer
      command: go test -timeout 30s -race -coverprofile=coverage.txt -covermode=atomic ./cmd/... ./pkg/...

  lint:
    containers:
    - <<: *baseGoContainer
      command: golangci-lint run ./cmd/... ./pkg/...

################################################################################
# Build / publish targets                                                      #
################################################################################

  clean:
    containers:
    - <<: *baseGoContainer
      command: rm -rf bin/

  build-cli-linux-amd64:
    containers:
    - <<: *baseGoContainer
      environment:
      - CGO_ENABLED=0
      command: scripts/build-cli.sh linux amd64

  build-cli-darwin-amd64:
    containers:
    - <<: *baseGoContainer
      environment:
      - CGO_ENABLED=0
      command: scripts/build-cli.sh darwin amd64

  build-cli-windows-amd64:
    containers:
    - <<: *baseGoContainer
      environment:
      - CGO_ENABLED=0
      command: scripts/build-cli.sh windows amd64

  # This requires a lot of privilege to run and may be useful locally, but
  # favor the DinD varient for use in CI/CD pipelines.
  build-brigade-worker-dood:
    containers:
    - <<: *baseDoodContainer
      command: scripts/build-brigade-worker-dood.sh

  build-brigade-worker-dind:
    containers:
    - <<: *baseDindContainer
      command: scripts/build-brigade-worker-dind.sh

  publish-cli:
    containers:
    - <<: *baseGoContainer
      command: scripts/publish-cli.sh

  # This requires a lot of privilege to run and may be useful locally, but
  # favor the DinD varient for use in CI/CD pipelines.
  publish-brigade-worker-dood:
    containers:
    - <<: *baseDoodContainer
      command: scripts/publish-brigade-worker-dood.sh

  publish-brigade-worker-dind:
    containers:
    - <<: *baseDindContainer
      command: scripts/publish-brigade-worker-dind.sh

################################################################################
# Pipelines                                                                    #
################################################################################

pipelines:

################################################################################
# Demo pipelines                                                               #
################################################################################

  foobar:
    stages:
    - targets:
      - foo
      - bar

################################################################################
# Utility pipelines                                                            #
################################################################################

  publish-brigade-worker-dood:
    stages:
    - targets:
      - build-brigade-worker-dood
    - targets:
      - publish-brigade-worker-dood

################################################################################
# CI pipelines                                                                 #
################################################################################

  test:
    criteria:
      branches:
        ignore:
        - master
    stages:
    - targets:
      - env
    - targets:
      - lint
      - verify-vendored-code
      - test-unit
    - targets:
      - build-cli-linux-amd64
      - build-cli-darwin-amd64
      - build-cli-windows-amd64
      - build-brigade-worker-dind

  master:
    criteria:
      branches:
        only:
        - master
    stages:
    - targets:
      - env
    - targets:
      - lint
      - verify-vendored-code
      - test-unit
    - targets:
      - build-cli-linux-amd64
      - build-cli-darwin-amd64
      - build-cli-windows-amd64
      - build-brigade-worker-dind
    - targets:
      - publish-brigade-worker-dind


################################################################################
# Release pipeline                                                             #
################################################################################

  release:
    criteria:
      tags:
        only:
        - /v[0-9]+(\.[0-9]+)*(\-.+)?/
    stages:
    - targets:
      - env
    - targets:
      - build-cli-linux-amd64
      - build-cli-darwin-amd64
      - build-cli-windows-amd64
      - build-brigade-worker-dind
    - targets:
      - publish-cli
      - publish-brigade-worker-dind
